### ISSUE TITLE
after selecting razorpay and click on continue got this error Error setting up the request: Invalid request: Unrecognized fields: 'context'

### ISSUE THREAD

**Issue by OmkarHalpatrao** [SGFTech/payment-razorpay#4]
![Image](https://github.com/user-attachments/assets/01953542-9b2b-49d0-9e4f-cab597be81cb)
i am getting this error
 when i comment context from this code 
`try {
      const shouldInputCard =
        isStripeFunc(selectedPaymentMethod) && !activeSession

      if (!activeSession) {
        await initiatePaymentSession(cart, {
          provider_id: selectedPaymentMethod,
          context:{
            extra:cart
          }
        })
      }
 }`
 .. and if i send context also then it give this error

![Image](https://github.com/user-attachments/assets/b248f196-eac8-4dc3-9801-cd5405e901fc)

**Comment by Balu-Varanasi** [comment]
@OmkarHalpatrao, I'm facing the same issue. @SGFGOV, it looks like some changes in the Medusa repo are impacting this - https://github.com/medusajs/medusa/commit/59cbc0ec77260e5be591e231e686445b0a8088cb#diff-375bd2e3f28f667a8689f7004d58b2d081298613b6a2a2f7d660d4006398b8c6

**Comment by Balu-Varanasi** [comment]
@SGFGOV, I can work on this issue, make the necessary changes, and raise a PR. Can you share your thoughts, guide me, and explain how to approach this?

**Comment by SGFGOV** [comment]
It's really not an issue.. The client needs to pass the cart component down to the server else the server has no way to know which payment session

**Comment by OmkarHalpatrao** [comment]
> It's really not an issue.. The client needs to pass the cart component down to the server else the server has no way to know which payment session

but thats we are passing with context right ?, but its gives error as context is unrecognised field. And i went through code and e i guess everywhere the context is declared ,so i am unable to figure it out why it is giving error.

**Comment by Balu-Varanasi** [comment]
@SGFGOV The MedusaJS API has been changed. The `context`  key is unavailable now. We need to make the corresponding changes in this repo, too. https://github.com/SGFTech/payment-razorpay/blob/master/src/core/razorpay-base.ts#L498

**Comment by SGFGOV** [comment]
Go ahead.. :)..and submit pr with tests

**Comment by Balu-Varanasi** [comment]
Sure

**Comment by OmkarHalpatrao** [comment]
> Sure

@Balu-Varanasi did you resolved that error, or pls update me issue is resolved
Thank  you

**Comment by Kartik18g** [comment]
Hey, do we have any updates on this fix ?

**Comment by Balu-Varanasi** [comment]
@OmkarHalpatrao @Kartik18g I'm working on the required changes. Should be able to raise a concrete PR within a day or two. Working on this after my office hours.

**Comment by Kartik18g** [comment]
Thanks for the update. I checked myself as well, seems like medusa changed a lot of things `CreatePaymentProviderSession`,`PaymentProviderError`,`PaymentProviderSessionResponse`, `UpdatePaymentProviderSession` no longer exist in `@medusajs/framework/types` and `isPaymentProviderError` is no longer in utils. Plus the deprecation of extra field for payment initialisation as @OmkarHalpatrao said.

**Comment by Balu-Varanasi** [comment]
@SGFGOV @OmkarHalpatrao @Kartik18g : Please check the PR - https://github.com/SGFTech/payment-razorpay/pull/6. We need to update the test cases. I would be happy if someone could contribute to them.

**Comment by Balu-Varanasi** [comment]
Also, I had to change the `initiatePaymentSession` function as below in `src/lib/data/cart.ts` to adhere to the latest medusa API.

Before:

```typescript
     ...
  return sdk.store.payment
    .initiatePaymentSession(cart, data, {}, headers)
    .then(async (resp) => {
      const cartCacheTag = await getCacheTag("carts")
      revalidateTag(cartCacheTag)
      return resp
    })
    .catch(medusaError)
    ...
```

After:

```typescript
    ...
  return sdk.store.payment
    .initiatePaymentSession(cart, {
      provider_id: data.provider_id,
      data: data.context,
    }, {}, headers)
    .then(async (resp) => {
      const cartCacheTag = await getCacheTag("carts")
      revalidateTag(cartCacheTag)
      return resp
    })
    .catch(medusaError)
   ...
```


Complete change:

```typescript
export async function initiatePaymentSession(
  cart: HttpTypes.StoreCart,
  data: {
    provider_id: string
    context?: Record<string, unknown>
  }
) {
  const headers = {
    ...(await getAuthHeaders()),
  }

  return sdk.store.payment
    .initiatePaymentSession(cart, {
      provider_id: data.provider_id,
      data: data.context,
    }, {}, headers)
    .then(async (resp) => {
      const cartCacheTag = await getCacheTag("carts")
      revalidateTag(cartCacheTag)
      return resp
    })
    .catch(medusaError)
}
```

**Comment by Kartik18g** [comment]
Hey, can take it up if you can give an overview because I don't have any experience writing tests.

**Comment by Kartik18g** [comment]
Hey @Balu-Varanasi any update on this ? I tried your branch but i'm getting `Error: You must pass a non-undefined value to the property data of entity PaymentSession.` this error. There was another issue which was because of user not creating in razorpay but fixed it myself. Can you provide any insights on the issue, this is literally a blocker for us.

**Comment by Kartik18g** [comment]
Hey @Balu-Varanasi I tried your branch but it still doesn't work. `error:   Error was thrown trying to authorize payment session - payses_01JP3CD38DAB8K0S58037VEVD1 - Error: You must pass a non-undefined value to the property data of entity PaymentSession.` getting this when i try to complete a payment and select success in test mode. Not sure if i'm doing something wrong or is it a bug.

**Comment by Balu-Varanasi** [comment]
@Kartik18g: Even I'm running into different issues, one after the other. With my free time, this seems like a rabbit hole to crack. I still need more time to understand the Medusajs payment flow and approach this issue correctly.

**Comment by Kartik18g** [comment]
I did a deepdive into it and found out that `authorizePayment` needs 2 things status and data (https://docs.medusajs.com/resources/references/payment/provider#authorizepayment). In your PR we are not passing data to it, so what i did is this ` paymentStatusResponse.data = razorpayOrder`. 
And now everything works fine, i'm able to capture the payment as well.
If you want i can raise a draft PR for this

**Comment by Balu-Varanasi** [comment]
@Kartik18g: You are fantastic, man! Yes, please raise a PR.

**Comment by OmkarHalpatrao** [comment]
@Balu-Varanasi @Kartik18g can you guide me how can i use it.

**Comment by Kartik18g** [comment]
> [@Kartik18g](https://github.com/Kartik18g): You are fantastic, man! Yes, please raise a PR.

Will raise it this weekend

**Comment by Kartik18g** [comment]
> [@Balu-Varanasi](https://github.com/Balu-Varanasi) [@Kartik18g](https://github.com/Kartik18g) can you guide me how can i use it.
So you'll need to first clone @Balu-Varanasi 's forked repo and checkout to the branch with fix. Then install the dependencies and build. 
Once built, install the local npm package instead of the published one on npm in medusa admin.

**Comment by Balu-Varanasi** [comment]
Kartik, take it is easy man. I'll make the changes on a new branch tomorrow. I'll try fix tests as well. @Kartik18g

**Comment by Balu-Varanasi** [comment]
If I can make these changes, I'll focus on medusa-payment-payu repo changes as well

**Comment by Balu-Varanasi** [comment]
> > [@Balu-Varanasi](https://github.com/Balu-Varanasi) [@Kartik18g](https://github.com/Kartik18g) can you guide me how can i use it.
> > So you'll need to first clone [@Balu-Varanasi](https://github.com/Balu-Varanasi) 's forked repo and checkout to the branch with fix. Then install the dependencies and build.
> > Once built, install the local npm package instead of the published one on npm in medusa admin.

Yes! You are right

**Comment by OmkarHalpatrao** [comment]
**I'm trying to set up the Medusa Razorpay Plugin, but I'm encountering the following error when starting the server:**

**i have clone your repo and checkout to the branch with fix**
`Could not resolve module: Payment. Error: Errors while loading module providers for module payment:
Cannot find module 'ajv/dist/core'
Require stack:
- D:\web development\medusa-razorpay-plugin\payment-razorpay\node_modules\ajv-draft-04\dist\index.js
- D:\web development\medusa-razorpay-plugin\payment-razorpay\node_modules\@rushstack\node-core-library\lib\JsonSchema.js
- D:\web development\medusa-razorpay-plugin\payment-razorpay\node_modules\@rushstack\node-core-library\lib\index.js
- D:\web development\medusa-razorpay-plugin\payment-razorpay\node_modules\@rushstack\terminal\lib\NormalizeNewlinesTextRewriter.js
...`

What I've Tried:
Deleted node_modules and package-lock.json and ran npm install again.
Tried installing ajv manually using npm install ajv@8.
Confirmed that the ajv-draft-04 package is installed.
Checked the package.json file to confirm dependencies.

**Comment by OmkarHalpatrao** [comment]
@Kartik18g @Balu-Varanasi is plugin ready to use.

**Comment by Kartik18g** [comment]
> **I'm trying to set up the Medusa Razorpay Plugin, but I'm encountering the following error when starting the server:**
> 
> **i have clone your repo and checkout to the branch with fix** `Could not resolve module: Payment. Error: Errors while loading module providers for module payment: Cannot find module 'ajv/dist/core' Require stack:
> 
> * D:\web development\medusa-razorpay-plugin\payment-razorpay\node_modules\ajv-draft-04\dist\index.js
> * D:\web development\medusa-razorpay-plugin\payment-razorpay\node_modules@rushstack\node-core-library\lib\JsonSchema.js
> * D:\web development\medusa-razorpay-plugin\payment-razorpay\node_modules@rushstack\node-core-library\lib\index.js
> * D:\web development\medusa-razorpay-plugin\payment-razorpay\node_modules@rushstack\terminal\lib\NormalizeNewlinesTextRewriter.js
>   ...`
> 
> What I've Tried: Deleted node_modules and package-lock.json and ran npm install again. Tried installing ajv manually using npm install ajv@8. Confirmed that the ajv-draft-04 package is installed. Checked the package.json file to confirm dependencies.

use pnpm instead of npm, ` npx pnpm@10.5.2 run build   ` I used this command to build the plugin before use

**Comment by prajwalr308** [comment]
is this working ? I am facing the same issue

**Comment by SGFGOV** [comment]
you are all using the wrong plugin..  you need to use medusa-plugin-razorpay-v2

**Comment by Kartik18g** [comment]
> you are all using the wrong plugin.. you need to use medusa-plugin-razorpay-v2

@SGFGOV can you link it, can’t seem to find it

**Comment by SGFGOV** [comment]
I've released the npm. you need a to wait a few days for the github repo..

**Comment by prajwalr308** [comment]
@SGFGOV  Is the read me updated for medusa-plugin-razorpay-v2?
I am still getting error that unrecognised fields : context

**Comment by SGFGOV** [comment]
Hmm.guess I updated it only in the provider not the main readme..Will fix it shortly

**Comment by SGFGOV** [comment]
# Payment-Razorpay

# Support the Payment-Razorpay Provider - Elevate Our Medusa Community!

Dear Developers and E-commerce Enthusiasts,

Are you ready to revolutionize the world of online stores with MedusaJS? We have an exciting opportunity that will make payment processing a breeze for our beloved Medusa platform! Introducing the Payment-Razorpay provider, a community-driven project that brings the immensely popular [RAZORPAY](https://razorpay.com) payment gateway to our MedusaJS commerce stack.

**What's in it for You:**

🚀 Streamline Payment Processing: With Payment-Razorpay, you can unleash the full potential of Razorpay's features, ensuring seamless and secure payments for your customers.

🌐 Global Reach: Engage with customers worldwide, as Razorpay supports various currencies and payment methods, catering to a diverse audience.

🎉 Elevate Your Medusa Store: By sponsoring this provider, you empower the entire Medusa community, driving innovation and success across the platform.

## Installation Made Simple

No hassle, no fuss! Install Payment-Razorpay effortlessly with npm:



[RAZORPAY](https://razorpay.com) an immensely popular payment gateway with a host of features. 
This provider enables the razorpay payment interface on [medusa](https://medusajs.com) commerce stack

## Installation

Use the package manager npm to install Payment-Razorpay.

```bash
npm install @sgftech/payment-razorpay
```

## Usage


Register for a razorpay account and generate the api keys
In your environment file (.env) you need to define 
```
RAZORPAY_ID=<your api key>
RAZORPAY_SECRET=<your api key secret>
RAZORPAY_ACCOUNT=<your razorpay account number/merchant id>
RAZORPAY_WEBHOOK_SECRET=<your web hook secret as defined in the webhook settings in the razorpay dashboard >
```
You need to add the provider into your medusa-config.ts as shown below

```
module.exports = defineConfig({
modules: [
  ...
    {      resolve: "@medusajs/medusa/payment",
      options: {
        providers: [
          ...
          {
            resolve: "@sgftech/payment-razorpay",
            id: "razorpay",
            options: {
              key_id:
                  process?.env?.RAZORPAY_TEST_KEY_ID ??
                  process?.env?.RAZORPAY_ID,
              key_secret:
                  process?.env?.RAZORPAY_TEST_KEY_SECRET ??
                  process?.env?.RAZORPAY_SECRET,
              razorpay_account:
                  process?.env?.RAZORPAY_TEST_ACCOUNT ??
                  process?.env?.RAZORPAY_ACCOUNT,
              automatic_expiry_period: 30 /* any value between 12minuts and 30 days expressed in minutes*/,
              manual_expiry_period: 20,
              refund_speed: "normal",
              webhook_secret:
                  process?.env?.RAZORPAY_TEST_WEBHOOK_SECRET ??
                  process?.env?.RAZORPAY_WEBHOOK_SECRET
          }
          },
          ....
        ],
     } },
  ...]
})
```
## Client side configuration


For the NextJs start you need to  make the following changes 

1. Install package to your next starter. This just makes it easier, importing all the scripts implicitly
```
yarn add react-razorpay

```
2. Create a button for Razorpay <next-starter>/src/modules/checkout/components/payment-button/razorpay-payment-button.tsx

like below



```

import { Button } from "@medusajs/ui"
import Spinner from "@modules/common/icons/spinner"
import React, { useCallback, useEffect, useState } from "react"
import  {useRazorpay, RazorpayOrderOptions } from "react-razorpay"
import { HttpTypes } from "@medusajs/types"
import {  placeOrder,  } from "@lib/data/cart"
import { CurrencyCode } from "react-razorpay/dist/constants/currency"
export const RazorpayPaymentButton = ({
  session,
  notReady,
  cart
}: {
  session: HttpTypes.StorePaymentSession
  notReady: boolean
  cart: HttpTypes.StoreCart
}) => {
  const [disabled, setDisabled] = useState(false)
  const [submitting, setSubmitting] = useState(false)
  const [errorMessage, setErrorMessage] = useState<string | undefined>(undefined)
  const {Razorpay
   } = useRazorpay();
  
  const [orderData,setOrderData] = useState({razorpayOrder:{id:""}})

  
  console.log(`session_data: `+JSON.stringify(session))
  const onPaymentCompleted = async () => {
    await placeOrder().catch(() => {
      setErrorMessage("An error occurred, please try again.")
      setSubmitting(false)
    })
  }
  useEffect(()=>{
    setOrderData(session.data as {razorpayOrder:{id:string}})
  },[session.data])

  


  const handlePayment = useCallback(async() => {
    const onPaymentCancelled = async () => {
        setErrorMessage("PaymentCancelled")
        setSubmitting(false)
      }
    
    const options: RazorpayOrderOptions = {
      key:process.env.NEXT_PUBLIC_RAZORPAY_KEY_ID??process.env.NEXT_PUBLIC_RAZORPAY_TEST_KEY_ID??"your_key_id",
      callback_url: `${process.env.NEXT_PUBLIC_MEDUSA_BACKEND_URL}/razorpay/hooks`,
      amount: session.amount*100*100,
      order_id: orderData.razorpayOrder.id,
      currency: cart.currency_code.toUpperCase() as CurrencyCode,
      name: process.env.COMPANY_NAME ?? "your company name ",
      description: `Order number ${orderData.razorpayOrder.id}`,
      remember_customer:true,
      

      image: "https://example.com/your_logo",
      modal: {
        backdropclose: true,
        escape: true,
        handleback: true,
        confirm_close: true,
        ondismiss: async () => {
          setSubmitting(false)
          setErrorMessage(`payment cancelled`)
          await onPaymentCancelled()
        },
        animation: true,
      },
      
      handler: async () => {
        onPaymentCompleted()
      },
      "prefill": {
        "name": cart.billing_address?.first_name + " " + cart?.billing_address?.last_name,
        "email": cart?.email,
        "contact": (cart?.shipping_address?.phone) ?? undefined
      },
      
      
    };
    console.log(JSON.stringify(options.amount))
    //await waitForPaymentCompletion();
    
    
    const razorpay = new Razorpay(options);
    if(orderData.razorpayOrder.id)
    razorpay.open();
    razorpay.on("payment.failed", function (response: any) {
      setErrorMessage(JSON.stringify(response.error))
   
    })
   razorpay.on("payment.authorized" as any, function (response: any) {
    const authorizedCart = placeOrder().then(authorizedCart=>{
    JSON.stringify(`authorized:`+ authorizedCart)
    })
    })
    // razorpay.on("payment.captured", function (response: any) {

    // }
    // )
  }, [Razorpay, cart.billing_address?.first_name, 
    cart.billing_address?.last_name, cart.currency_code,
     cart?.email, cart?.shipping_address?.phone, orderData.razorpayOrder.id, 
     session.amount, session.provider_id]);
  console.log("orderData"+JSON.stringify(orderData))
  return (
    <>
      <Button
        disabled={submitting || notReady || !orderData?.razorpayOrder?.id||orderData?.razorpayOrder?.id == ''}
        onClick={()=>{
          console.log(`processing order id: ${orderData.razorpayOrder.id}`)
          handlePayment()}
        }
      >
        {submitting ? <Spinner /> : "Checkout"}
      </Button>
      {errorMessage && (
        <div className="text-red-500 text-small-regular mt-2">
          {errorMessage}
        </div>
      )}
    </>
  )
}
```

Step 3. 

nextjs-starter-medusa/src/lib/constants.tsx
add

```
export const isRazorpay = (providerId?: string) => {
  return providerId?.startsWith("pp_razorpay")
}

// and the following to the list
export const paymentInfoMap: Record<
  string,
  { title: string; icon: React.JSX.Element }
> = {...
   pp_razorpay_razorpay: {
    title: "Razorpay",
    icon: <CreditCard />,
  },
  ...}

````
step 4.add into the payment element <next-starter>/src/modules/checkout/components/payment-button/index.tsx

first 
```
import import {RazorpayPaymentButton} from "./razorpay-payment-button"
```
then
```
case "razorpay":
         return <RazorpayPaymentButton session={paymentSession} notReady={notReady} cart={cart} />
```



Step 4. Add environment variables in the client

  NEXT_PUBLIC_RAZORPAY_KEY:<your razorpay key>
  NEXT_PUBLIC_SHOP_NAME:<your razorpay shop name>
  NEXT_PUBLIC_SHOP_DESCRIPTION: <your razorpayshop description>
#### watch out
Step 6. Caveat 
the default starter template has an option which says use the same shipping and billing address
please ensure you deselect this and enter the phone number manually in the billing section.

Step 7.

In razorpay create a webhook with the following url 

<your host>/hooks/payment/razorpay_razorpay

## Contributing


Pull requests are welcome. For major changes, please open an issue first to discuss what you would like to change.

Please make sure to update tests as appropriate.

## License
[MIT](https://choosealicense.com/licenses/mit/)

## Untested features

These features exists, but without implementing the client it isn't possible to tests these outright

1. Capture Payment
2. Refund


## Disclaimer
The code was tested on limited number of usage scenarios. There maybe unforseen bugs, please raise the issues as they come, or create pull requests if you'd like to submit fixes.


## Support the Payment-Razorpay Provider - Strengthen Our Medusa Community!

Dear Medusa Enthusiasts,

I hope this message finds you all in high spirits and enthusiasm for the world of e-commerce! Today, I reach out to our vibrant Medusa community with a heartfelt appeal that will strengthen our collective journey and elevate our online stores to new heights. I am thrilled to present the Payment-Razorpay provider, a community-driven project designed to streamline payment processing for our beloved Medusa platform.

As a dedicated member of this community, I, SGFGOV, have invested my time and passion into crafting this valuable provider that bridges the gap between online retailers and their customers. It is with great humility that I invite you to participate in this open-source initiative by [sponsoring the Payment-Razorpay provider through GitHub](https://github.com/sponsors/SGFGOV).

Your sponsorship, no matter the size, will make a world of difference in advancing the Medusa ecosystem. It will empower me to focus on the continuous improvement and maintenance of the Payment-Razorpay provider, ensuring it remains reliable, secure, and seamlessly integrated with Medusa.

Being a community provider, perks are not the focus of this appeal. Instead, I promise to give back to the community by providing fast and efficient support via Discord or any other means. Your sponsorship will help sustain and enhance the provider's development, allowing me to be responsive to your needs and address any concerns promptly.

Let's come together and demonstrate the power of community collaboration. By [sponsoring the Payment-Razorpay provider on GitHub](https://github.com/sponsors/SGFGOV), you directly contribute to the success of not only this project but also the broader Medusa ecosystem. Your support enables us to empower developers, merchants, and entrepreneurs, facilitating growth and success in the world of e-commerce.

To show your commitment and be part of this exciting journey, kindly consider [sponsoring the Payment-Razorpay provider on GitHub](https://github.com/sponsors/SGFGOV). Your contribution will amplify the impact of our community and foster a supportive environment for all.

Thank you for your time, and thank you for being an integral part of our Medusa community. Together, we will elevate our online stores and create extraordinary experiences for customers worldwide.

With warm regards,

SGFGOV
Lead Developer, Payment-Razorpay Provider for Medusa

**Comment by SGFGOV** [comment]
just posted the readme until i get a chance to update readmes

**Comment by prajwalr308** [comment]
@SGFGOV  In the readme It's using @sgftech/payment-razorpay not medusa-plugin-razorpay-v2. Is this right ?

**Comment by SGFGOV** [comment]
https://github.com/SGFGOV/medusa-payment-plugins

**Comment by Balu-Varanasi** [comment]
This is great - Thank you, Govid! @SGFGOV :)

**Comment by Kartik18g** [comment]
I tried the instructions here https://www.npmjs.com/package/medusa-plugin-razorpay-v2 , but getting `Unable to retrieve the payment provider with id: pp_razorpay_razorpay` . Would be amazing if you guys can provide some clarity on what to actually use.

**Comment by SGFGOV** [comment]
Check provider docs

**Comment by Kartik18g** [comment]
Followed exactly https://medusajs.com/integrations/medusa-plugin-razorpay-v2/ and the same error is persistent. 😢

**Comment by OmkarHalpatrao** [comment]
> Followed exactly https://medusajs.com/integrations/medusa-plugin-razorpay-v2/ and the same error is persistent. 😢

i also tried the  exact same  steps  given in docs and getting the same error.

**Comment by SGFGOV** [comment]
the page is outdated.. please use this https://github.com/SGFGOV/medusa-payment-plugins/tree/master/packages/medusa-plugin-razorpay-v2
